"""add unique constraint to payment audit idempotency key

Revision ID: b7fce0c8745b
Revises: 713fc3c55690
Create Date: 2026-09-27 20:55:55.699928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fce0c8745b'
down_revision: Union[str, Sequence[str], None] = '713fc3c55690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
